name: 'Ponicode DogString: Automatic AI-based Docstring generation'
description: 'Add doctrings to all your undocumented functions in your repository'
branding:
  icon: 'align-justify'  
  color: 'orange'
inputs: 
  repo_path:
    description: 'Path of repo to generate docstrings for'
    required: true
    default: './'
  auth_token:
    description: 'The Ponicode token'
    required: true
  all_repo:
    description: 'Boolean: choose using the action on all the repository or just on the last commit'
    required: true
    default: False
  enable_template:
    description: 'Boolean: enable params and templates in the docstrings'
    required: false
    default: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_path }}
    - ${{ inputs.auth_token }}
    - ${{ inputs.all_repo }}
    - ${{ inputs.enable_template }}
